# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import inference_pb2 as inference__pb2

GRPC_GENERATED_VERSION = '1.83.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in inference_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class InferenceServiceStub:
    """核心服务定义
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Infer = channel.unary_unary(
                '/stanzixinwan.inference.v1.InferenceService/Infer',
                request_serializer=inference__pb2.InferenceRequest.SerializeToString,
                response_deserializer=inference__pb2.InferenceResponse.FromString,
                _registered_method=True)
        self.InferStream = channel.unary_stream(
                '/stanzixinwan.inference.v1.InferenceService/InferStream',
                request_serializer=inference__pb2.InferenceRequest.SerializeToString,
                response_deserializer=inference__pb2.InferenceResponse.FromString,
                _registered_method=True)


class InferenceServiceServicer:
    """核心服务定义
    """

    def Infer(self, request, context):
        """单次推理（非流式）
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def InferStream(self, request, context):
        """流式推理：服务端逐 token 推送
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_InferenceServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Infer': grpc.unary_unary_rpc_method_handler(
                    servicer.Infer,
                    request_deserializer=inference__pb2.InferenceRequest.FromString,
                    response_serializer=inference__pb2.InferenceResponse.SerializeToString,
            ),
            'InferStream': grpc.unary_stream_rpc_method_handler(
                    servicer.InferStream,
                    request_deserializer=inference__pb2.InferenceRequest.FromString,
                    response_serializer=inference__pb2.InferenceResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'stanzixinwan.inference.v1.InferenceService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('stanzixinwan.inference.v1.InferenceService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class InferenceService:
    """核心服务定义
    """

    @staticmethod
    def Infer(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/stanzixinwan.inference.v1.InferenceService/Infer',
            inference__pb2.InferenceRequest.SerializeToString,
            inference__pb2.InferenceResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def InferStream(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/stanzixinwan.inference.v1.InferenceService/InferStream',
            inference__pb2.InferenceRequest.SerializeToString,
            inference__pb2.InferenceResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class WorkerControlStub:
    """调度层与 Worker 之间的控制面通信
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ReportHealth = channel.stream_stream(
                '/stanzixinwan.inference.v1.WorkerControl/ReportHealth',
                request_serializer=inference__pb2.HealthReport.SerializeToString,
                response_deserializer=inference__pb2.HealthAck.FromString,
                _registered_method=True)


class WorkerControlServicer:
    """调度层与 Worker 之间的控制面通信
    """

    def ReportHealth(self, request_iterator, context):
        """Worker 定期上报健康状态
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_WorkerControlServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ReportHealth': grpc.stream_stream_rpc_method_handler(
                    servicer.ReportHealth,
                    request_deserializer=inference__pb2.HealthReport.FromString,
                    response_serializer=inference__pb2.HealthAck.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'stanzixinwan.inference.v1.WorkerControl', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('stanzixinwan.inference.v1.WorkerControl', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class WorkerControl:
    """调度层与 Worker 之间的控制面通信
    """

    @staticmethod
    def ReportHealth(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/stanzixinwan.inference.v1.WorkerControl/ReportHealth',
            inference__pb2.HealthReport.SerializeToString,
            inference__pb2.HealthAck.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
